[package]
name = "aoc_2015_rs"
version = "1.0.0"
edition = "2021"
authors = ["rhelv"]
# default-run = "aoc"

[lib]
proc-macro = true

[profile.dev]
overflow-checks = false

[dependencies]
itertools = "0.12.0"
hashbrown = "0.14.3"
serde_json = "1.0.108"
rayon = "1.8.0"
time = "0.3.30"